export const interviewCopy = {
  en: {
    title: "Shape your reading",
    intro: "These are preferences, not a test. There are no right answers or scores.",
    progress: "Saved",
    of: "of",
    suggested: "suggested steps",
    browse: "Browse all lenses",
    review: "Review saved answers",
    save: "Save choices",
    custom: "Your own response",
    saveCustom: "Save custom response",
    unsure: "Not sure yet",
    skip: "Skip this question",
    back: "Back",
    next: "Next",
    edit: "Edit",
    saved: "Answer saved. You can change it anytime.",
    hint: "Save your response before navigating or changing language. Each save replaces your previous response.",
    required:
      "Required decision — cannot be skipped. This records your decision only; it does not authorize a later workflow.",
    range: "Select",
    to: "to",
    choices: "choices",
    empty: "No saved answer",
    customSaved: "Custom response",
    skipped: "Skipped",
    error:
      "Response not saved. Choose within the stated limit, or use one alternative response. This question may have changed; review the current choices.",
    complete: "Suggested responses saved",
    pending: "Required decisions still need a response",
    return: "Return to interview",
  },
  ja: {
    title: "読書の方向を整える",
    intro: "これは好みを知るための質問です。正解や点数はありません。",
    progress: "保存済み",
    of: "/",
    suggested: "おすすめの質問",
    browse: "すべての視点を見る",
    review: "保存した回答を確認",
    save: "選択を保存",
    custom: "自分の言葉で回答",
    saveCustom: "自由回答を保存",
    unsure: "まだわからない",
    skip: "この質問をスキップ",
    back: "戻る",
    next: "次へ",
    edit: "編集",
    saved: "回答を保存しました。いつでも変更できます。",
    hint: "移動や言語の切り替えの前に回答を保存してください。保存すると以前の回答を置き換えます。",
    required: "必須の判断です。スキップできません。判断の記録のみで、後続の処理は承認されません。",
    range: "選択数：",
    to: "〜",
    choices: "個",
    empty: "未回答",
    customSaved: "自由回答",
    skipped: "スキップ済み",
    error:
      "回答は保存されませんでした。指定された数を選ぶか、別の回答方法を一つ使ってください。質問が更新された可能性もあるため、現在の選択肢を確認してください。",
    complete: "おすすめの回答を保存しました",
    pending: "必須の判断がまだ回答されていません",
    return: "質問に戻る",
  },
} as const
export type InterviewLanguage = keyof typeof interviewCopy
